FROM benchflow/base-images:dns-envconsul-java8_dev

MAINTAINER Vincenzo FERME <info@vincenzoferme.it>

COPY configuration.yml /app/

COPY ./services/envcp/config.tpl /app/config.tpl

COPY ./target/benchflow-experiments-manager.jar /app/
COPY ./services/300-experiments-manager.conf /apps/chaperone.d/300-experiments-manager.conf
 
EXPOSE 8080
