engines:
  checkstyle:
    enabled: true
    channel: "beta"
  scalastyle:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true

ratings:
  paths:
    - "**.java"
    - "**.scala"

exclude_paths:
- "**/src/test/**"