sudo: required
dist: precise
group: edge

language: java
jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - dev
  except:
    - v-dev

install:
  - make install

script:
  - make test

cache:
  directories:
    - $HOME/.m2
    - /usr/bin

before_deploy:
  # Clean the v-dev release and tag we are using to release development version in CI
  - sudo wget https://github.com/benchflow/devops/raw/dev/ci/clean_v-dev_release.sh -O /usr/bin/clean_v-dev_release.sh
  - sudo chmod +x /usr/bin/clean_v-dev_release.sh
  - export REPO_NAME=benchflow-dsl
  - /usr/bin/clean_v-dev_release.sh

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_ACCESS_TOKEN
  file:
    - target/benchflow-dsl.jar
  skip_cleanup: true
  on:
    tags: false
    repo: benchflow/benchflow-dsl
    branch: dev