experiments-manager:
  ports:
  - ${EXPERIMENTS_MANAGER_PORT}:8080/tcp
  environment:
    DB_ADDRESS: experiments-manager-mysql:3306
    DRIVERS_MAKER_ADDRESS: http://drivers-maker:8080
    ENVCONSUL_CONSUL: consul:${CONSUL_MASTER_PORT}
    FABAN_ADDRESS: http://faban:9980
    MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
    MINIO_ADDRESS: http://minio:${MINIO_PORT}
    MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    DB_PASSWORD: ${EXPERIMENTS_MANAGER_DB_PASSWORD}
  labels:
    io.rancher.sidekicks: experiments-manager-mysql
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: purpose=master
    io.rancher.container.hostname_override: container_name
  tty: true
  image: benchflow/experiments-manager:dev
  links:
  - faban-harness:faban
  - consul-master:consul
  - 'minio:'
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  stdin_open: true
data-analyses-scheduler:
  ports:
  - ${DATA_ANALYSIS_SCHEDULER_PORT}:8080/tcp
  environment:
    CASSANDRA_HOST: cassandra
    CASSANDRA_PORT: '${CASSANDRA_PORT}'
    ENVCONSUL_CONSUL: consul:${CONSUL_MASTER_PORT}
    MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
    MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    KAFKA_HOST: kafka
    MINIO_HOST: minio
    KAFKA_PORT: '${KAFKA_PRODUCERS_PORT}'
    MINIO_PORT: '${MINIO_PORT}'
    SPARK_MASTER: local[*]
    SPARK_PORT: '7077'
    DRIVER_MEMORY: 16g
    EXECUTOR_MEMORY: 16g
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: purpose=master
    io.rancher.container.hostname_override: container_name
  tty: true
  image: benchflow/data-analyses-scheduler:dev
  links:
  - consul-master:consul
  - 'kafka:'
  - 'minio:'
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  stdin_open: true
swarm-master:
  ports:
  - ${SWAM_MASTER_PORT}:2375/tcp
  labels:
    io.rancher.scheduler.affinity:host_label: purpose=master
    io.rancher.container.hostname_override: container_name
    io.rancher.container.dns: 'true'
  tty: true
  command:
  - manage
  - -H
  - tcp://${SWAM_MASTER_IP}:${SWAM_MASTER_PORT}
  - consul://consul:${CONSUL_MASTER_PORT}/swarm
  image: swarm:1.2.3
  links:
  - consul-master:consul
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  net: host
  stdin_open: true
swarm-agent-neha:
  labels:
    io.rancher.scheduler.affinity:host_label: name=neha
    io.rancher.container.hostname_override: container_name
    io.rancher.container.dns: 'true'
  tty: true
  command:
  - join
  - --advertise=${SWAM_AGENT_NEHA_IP}:${SWAM_AGENT_NEHA_PORT}
  - consul://consul:${CONSUL_MASTER_PORT}/swarm
  image: swarm:1.2.3
  links:
  - consul-master:consul
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  net: host
  stdin_open: true
faban-harness:
  ports:
  - ${FABAN_HARNESS_PORT}:9980/tcp
  environment:
    IS_RANCHER: 'true'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: purpose=master
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: faban-harness-data
  tty: true
  image: benchflow/faban:harness_dev
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  volumes_from:
  - faban-harness-data
  stdin_open: true
faban-harness-data:
  image: benchflow/faban:harness_dev
  command: /bin/true
  volumes:
  - /app/faban/master/logs
  - /app/faban//master/conf
  - /app/faban/output
  - /app/faban/benchmarks
  - /app/faban/config
  - /app/faban/logs
  - /app/faban/services
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  labels:
  io.rancher.container.hostname_override: container_name
  io.rancher.container.start_once: true
drivers-maker:
  ports:
  - ${DRIVERS_MAKER_PORT}:8080/tcp
  environment:
    ENVCONSUL_CONSUL: consul:${CONSUL_MASTER_PORT}
    MINIO_ADDRESS: http://minio:${MINIO_PORT}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: purpose=master
    io.rancher.container.hostname_override: container_name
  tty: true
  image: benchflow/drivers-maker:dev
  links:
  - consul-master:consul
  - 'minio:'
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  stdin_open: true
consul-master:
  ports:
  - ${CONSUL_MASTER_PORT}:8500/tcp
  labels:
    io.rancher.scheduler.affinity:host_label: purpose=master
    io.rancher.container.hostname_override: container_name
  tty: true
  command:
  - -server
  - -bootstrap
  - -ui-dir
  - /ui
  image: progrium/consul:latest
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  stdin_open: true
experiments-manager-mysql:
  environment:
    MYSQL_ROOT_PASSWORD: ${EXPERIMENTS_MANAGER_DB_PASSWORD}
    MYSQL_USER: root
    MYSQL_PASSWORD: ${EXPERIMENTS_MANAGER_DB_PASSWORD}
    MYSQL_DATABASE: experiments
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: purpose=master
    io.rancher.container.hostname_override: container_name
  tty: true
  image: mysql:5.7.13
  links:
  - faban-harness:faban
  - consul-master:consul
  - 'minio:'
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  stdin_open: true
cassandra:
  ports:
  - ${CASSANDRA_PORT}:9160/tcp
  environment:
    CASSANDRA_LISTEN_ADDRESS: cassandra
    CASSANDRA_RPC_ADDRESS: 0.0.0.0
    CASSANDRA_START_RPC: 'true'
    CASSANDRA_INITIALIZE: 'true'
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: cassandra-data
  tty: true
  image: benchflow/cassandra:dev
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  volumes_from:
  - cassandra-data
  stdin_open: true
cassandra-data:
  image: benchflow/cassandra:dev
  command: /bin/true
  volumes:
  - /var/lib/cassandra
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  labels:
  io.rancher.container.hostname_override: container_name
  io.rancher.container.start_once: true
kafka:
  ports:
  - ${KAFKA_PRODUCERS_PORT}:2181/tcp
  - ${KAFKA_CONSUMERS_PORT}:9092/tcp
  environment:
    ADVERTISED_HOST: ${KAFKA_ADVERTISED_HOST_IP}
    ADVERTISED_PORT: '${KAFKA_CONSUMERS_PORT}'
    AUTO_CREATE_TOPICS: 'true'
  labels:
    io.rancher.scheduler.affinity:host_label: purpose=master
    io.rancher.container.hostname_override: container_name
  tty: true
  image: benchflow/kafka:dev
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  stdin_open: true
faban-agent:
  environment:
    IS_RANCHER: 'true'
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: purpose=faban_agent
    io.rancher.container.hostname_override: container_name
  tty: true
  image: benchflow/faban:agent_dev
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  stdin_open: true
deployment-manager:
  ports:
  - ${DEPLOYMENT_MANAGER_PORT}:8080/tcp
  environment:
    BENCHFLOW_SWARM_ENDPOINT: ${SWAM_MASTER_IP}:${SWAM_MASTER_PORT}
    BENCHFLOW_SWARM_TLSVERIFY: '0'
    ENVCONSUL_CONSUL: consul:${CONSUL_MASTER_PORT}
  labels:
    io.rancher.scheduler.affinity:host_label: purpose=master
    io.rancher.container.hostname_override: container_name
  tty: true
  image: benchflow/deployment-manager:dev
  links:
  - consul-master:consul
  - swarm-master:swarm
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  stdin_open: true
minio:
  ports:
  - ${MINIO_PORT}:9000/tcp
  environment:
    MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
    MINIO_ALIAS: benchflow
    MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: purpose=master
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: minio-data
  tty: true
  image: benchflow/minio:dev
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  volumes_from:
  - minio-data
  stdin_open: true
minio-data:
  image: benchflow/minio:dev
  command: /bin/true
  volumes:
  - /benchflow
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  labels:
  io.rancher.container.hostname_override: container_name
  io.rancher.container.start_once: true
# tests-orchestrator:
#   ports:
#   - 8030:8080/tcp
#   environment:
#     DB_ADDRESS: http://tests-orchestrator-mysql:3306
#     EXPERIMENTS_MANAGER_ADDRESS: http://experiments-manager:8080
#     ENVCONSUL_CONSUL: consul:${CONSUL_MASTER_PORT}
#     MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
#     MINIO_ADDRESS: http://minio:${MINIO_PORT}
#     MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
#     DB_USER: benchflow
#     DB_PASSWORD: tests-orchestrator
#     KAFKA_ADDRESS: http://kafka:${KAFKA_PRODUCERS_PORT}
#   labels:
#     io.rancher.sidekicks: tests-orchestrator-mysql
#     io.rancher.container.pull_image: always
#     io.rancher.scheduler.affinity:host_label: purpose=master
#     io.rancher.container.hostname_override: container_name
#   tty: true
#   image: benchflow/test-orchestrator:dev
#   links:
#   - minio:minio
#   - kafka:kafka
#   - consul-master:consul
#   volumes:
#   - /etc/localtime:/etc/localtime:ro
#   - /etc/timezone:/etc/timezone:ro
#   stdin_open: true
# tests-orchestrator-mysql:
#   environment:
#     MYSQL_ROOT_PASSWORD: ~12345~asdqwe~
#     MYSQL_USER: benchflow
#     MYSQL_PASSWORD: tests-orchestrator
#   labels:
#     io.rancher.container.pull_image: always
#     io.rancher.scheduler.affinity:host_label: purpose=master
#     io.rancher.container.hostname_override: container_name
#   tty: true
#   image: mysql:5.7.13
#   links:
#   - minio:minio
#   - kafka:kafka
#   - consul-master:consul
#   volumes:
#   - /etc/localtime:/etc/localtime:ro
#   - /etc/timezone:/etc/timezone:ro
#   stdin_open: true
# data-manager:
#   ports:
#   - 8020:8080/tcp
#   environment:
#     ENVCONSUL_CONSUL: consul:${CONSUL_MASTER_PORT}
#   labels:
#     io.rancher.container.pull_image: always
#     io.rancher.scheduler.affinity:host_label: purpose=master
#     io.rancher.container.hostname_override: container_name
#   tty: true
#   image: benchflow/data-manager:dev
#   links:
#   - consul-master:consul
#   volumes:
#   - /etc/localtime:/etc/localtime:ro
#   - /etc/timezone:/etc/timezone:ro
#   stdin_open: true
# spark:
#   ports:
#   - 4040:4040/tcp
#   - 6066:6066/tcp
#   - 7077:7077/tcp
#   - 8095:8095/tcp
#   environment:
#     MASTER: spark://spark:7077
#     SPARK_MASTER_WEBUI_PORT: '8095'
#   labels:
#     io.rancher.sidekicks: spark-worker
#     io.rancher.scheduler.affinity:host_label: purpose=master
#     io.rancher.container.hostname_override: container_name
#   tty: true
#   command:
#   - bin/spark-class
#   - org.apache.spark.deploy.master.Master
#   - -h
#   - spark
#   image: gettyimages/spark:1.6.2-hadoop-2.6
#   links:
#   - 'minio:'
#   volumes:
#   - /etc/localtime:/etc/localtime:ro
#   - /etc/timezone:/etc/timezone:ro
#   stdin_open: true
# spark-worker:
#   ports:
#   - 8096:8096/tcp
#   environment:
#     SPARK_WORKER_PORT: '7078'
#     SPARK_WORKER_WEBUI_PORT: '8096'
#     SPARK_WORKER_MEMORY: 24g
#     SPARK_WORKER_CORES: '12'
#   labels:
#     io.rancher.scheduler.affinity:host_label: purpose=master
#     io.rancher.container.hostname_override: container_name
#   tty: true
#   command:
#   - bin/spark-class
#   - org.apache.spark.deploy.worker.Worker
#   - spark://spark:7077
#   image: gettyimages/spark:1.6.2-hadoop-2.6
#   links:
#   - 'minio:'
#   volumes:
#   - /etc/localtime:/etc/localtime:ro
#   - /etc/timezone:/etc/timezone:ro
#   stdin_open: true