# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           ./
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          ""
url:              ""
encoding:         UTF-8
exclude:          [assets/scss/]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom vars
current_version:  ""
repo:             https://github.com/benchflow/benchflow