BENCHFLOW_SERVERS_LIST_ALIASES: [ ${BENCHFLOW_SERVERS_LIST_ALIASES} ]
MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
BENCHFLOW_DEPLOYMENT_MANAGER_ADDRESS: "${BENCHFLOW_DEPLOYMENT_MANAGER_ADDRESS}"
BENCHFLOW_FABAN_AGENTS: [ ${BENCHFLOW_FABAN_AGENTS} ]
BENCHFLOW_FABAN_MASTER: "${BENCHFLOW_FABAN_MASTER}"
BENCHFLOW_KAFKA_IP: "${BENCHFLOW_KAFKA_IP}"
BENCHFLOW_KAFKA_PORT: "${BENCHFLOW_KAFKA_PORT}"
BENCHFLOW_MINIO_IP: "${BENCHFLOW_MINIO_IP}"
BENCHFLOW_MINIO_PORT: "${BENCHFLOW_MINIO_PORT}"
$(`/app/add_servers_info.sh`)